//SUMMARY:
//CONTEXT API:GLOBAL VARIABLE WHICH HAS ALL DATA
//STEP 1: CREATE CONTEXT FOLDER AND ADD A FILE USRCONTEXT.JS AND CREATE A CONTEXT THERE AND EXPORT IT
//NOW WE'LL MAKE A PROVIDER THROUGH THIS CONTEXT THT PROVIDES THE DATA TO ALL THE COMPONENTS WRITTEN INSIDE IT.ALL THE COMPONENTS IN THE CONTEXT CAN ACCESS THE STATE FROM CONTEXT.
//STEP 2:CREATE USERCONTEXTPROVIDER
//STEP 3: WRAP THE CHILDREN WITH USERCONTEXT PROVIDER
//STEP 4: WHAT WILL IT ACCESS? WHAT'S IT GONNA PROVIDE? WE NEED TO GIVE DATA SOWE CREATE STATE 
import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.jsx'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
